//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSys/Hotkey/Hotkey.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Hotkey: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Hotkey()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Hotkey"",
    ""maps"": [
        {
            ""name"": ""UiAction"",
            ""id"": ""0a9e3e89-5bac-43a7-9cb8-300e39754810"",
            ""actions"": [
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""062f4ed4-93fe-4d90-b712-67147fa99496"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""db3225fd-b067-433d-90e5-6fc043f5dca1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""45b7da87-9d97-4195-99cf-057c94ddca96"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5477b1d4-9094-4818-9d28-9e2db3aaa823"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        }
    ]
}");
        // UiAction
        m_UiAction = asset.FindActionMap("UiAction", throwIfNotFound: true);
        m_UiAction_Reset = m_UiAction.FindAction("Reset", throwIfNotFound: true);
        m_UiAction_Pause = m_UiAction.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UiAction
    private readonly InputActionMap m_UiAction;
    private List<IUiActionActions> m_UiActionActionsCallbackInterfaces = new List<IUiActionActions>();
    private readonly InputAction m_UiAction_Reset;
    private readonly InputAction m_UiAction_Pause;
    public struct UiActionActions
    {
        private @Hotkey m_Wrapper;
        public UiActionActions(@Hotkey wrapper) { m_Wrapper = wrapper; }
        public InputAction @Reset => m_Wrapper.m_UiAction_Reset;
        public InputAction @Pause => m_Wrapper.m_UiAction_Pause;
        public InputActionMap Get() { return m_Wrapper.m_UiAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UiActionActions set) { return set.Get(); }
        public void AddCallbacks(IUiActionActions instance)
        {
            if (instance == null || m_Wrapper.m_UiActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UiActionActionsCallbackInterfaces.Add(instance);
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IUiActionActions instance)
        {
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IUiActionActions instance)
        {
            if (m_Wrapper.m_UiActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUiActionActions instance)
        {
            foreach (var item in m_Wrapper.m_UiActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UiActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UiActionActions @UiAction => new UiActionActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IUiActionActions
    {
        void OnReset(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
